# Generated by Django 5.2.5 on 2026-09-05 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=150, unique=True)),
                ("store_id", models.BigIntegerField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="ONLINE", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("reference_type", models.CharField(blank=True, max_length=100)),
                ("reference_id", models.CharField(blank=True, max_length=120)),
                ("store_id", models.BigIntegerField(blank=True, null=True)),
                ("register_id", models.BigIntegerField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=150)),
                ("request_id", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="production__action_36455c_idx",
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="production__referen_941b6a_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="production__actor_i_33ea2f_idx",
                    ),
                ],
            },
        ),
    ]
