# Generated by Django 5.2.5 on 2026-09-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("POS", "POS"),
                            ("SCANNER", "Scanner"),
                            ("PRINTER", "Printer"),
                            ("SCALE", "Scale"),
                            ("DISPLAY", "Display"),
                            ("CASH_DRAWER", "Cash Drawer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("connection_type", models.CharField(default="NETWORK", max_length=30)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="stores.register",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="stores.store",
                    ),
                ),
            ],
        ),
    ]
