# Generated by Django 5.2.5 on 2026-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent_id", models.CharField(max_length=100, unique=True)),
                ("method", models.CharField(max_length=30)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="QAR", max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("AUTHORIZED", "Authorized"),
                            ("CAPTURED", "Captured"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIAL_REFUND", "Partial refund"),
                        ],
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=150)),
                ("idempotency_key", models.CharField(max_length=150, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
